### ISSUE TITLE
Calling whoami method without logged in (invalid access token) causes a server error

### ISSUE THREAD

**Issue by ChronosX88** [nxshock/signaller#4]
## Steps to reproduce
1. Login in the account
2. Logout from the account
3. Call whoami (`/_matrix/client/r0/account/whoami`) method
### Expected behavior
Responded as normally JSON error.
### Actual behavior
Server breaks the calling and print stacktrace of error in console.
#### Comment:
None

**Comment by nxshock** [comment]
e5b1dbd64334c93fcf8e04d43aa2139978f7ad8b

**Comment by ChronosX88** [comment]
Not fixed by this commit.
